### ISSUE TITLE
Implement item search - PBY

### ISSUE THREAD

**Issue by abartov** [projectbenyehuda/sara#20]
Verify search results are correct.  See Asaf's email with the example returning 100 results when the on-site search returns 7.

**Comment by damisul** [comment]
Copying message from email:

> When searching on the PBY site for וירג'יניה וולף, we get 7 results.  This seems correct to me.
> https://benyehuda.org/search/results/?q=%D7%95%D7%99%D7%A8%D7%92%27%D7%99%D7%A0%D7%99%D7%94%20%D7%95%D7%95%D7%9C%D7%A3
> 
> However, querying SARA for the same string yields 100 results.  Why is the API returning 100 results and not 7?

**Comment by damisul** [comment]
This should be fixed in PBY project, see https://github.com/abartov/bybeconv/issues/188

**Comment by damisul** [comment]
@abartov , I believe we can close this now?
